# Generated by Django 5.0.6 on 2024-07-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='Author Name')),
                ('author_mail', models.EmailField(max_length=200, verbose_name='Author Email')),
                ('post_text', models.TextField(max_length=5000, verbose_name='Post Text')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='Edit Time')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
            ],
        ),
    ]
