# Generated by Django 5.0.6 on 2024-07-06 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuestBook',
            new_name='GuestBookPosts',
        ),
    ]
