# Generated by Django 5.0.6 on 2024-07-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0003_rename_guestbookposts_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(default='active', max_length=50, verbose_name='Status'),
        ),
    ]
