# Generated by Django 5.0.6 on 2024-07-06 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0004_alter_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_text',
            new_name='text',
        ),
    ]
