# Generated by Django 5.0.6 on 2024-07-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0005_rename_post_text_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('blocked', 'blocked')], default='active', max_length=50, verbose_name='Status'),
        ),
    ]
